version: "3.3"
services:
  web:
    container_name: web
    build: "./frontend"
    volumes:
      - './:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start
  api:
    build: ./backend
    volumes:
      - ./backend:/home/node/app
    ports:
      - 3001:3001
    depends_on:
      - db
    environment:
      DB_URL: mongodb://db/example
  db:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    volumes:
      - vidly:/data/db
volumes:
  vidly: